# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift
# cache: cocoapods
# podfile: Example/Podfile

before_install:
- gem update cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
- set -o pipefail
- xcodebuild -workspace Example/AGVolumeControlView.xcworkspace -scheme AGVolumeControlView-Example -sdk iphonesimulator11.4 -destination "OS=10.13,name=iPhone X" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c;
- pod lib lint --allow-warnings
